apiVersion: v2
name: transformer
description: A Helm chart for Kafka Message Transformer service
type: application
version: 1.0.1
appVersion: "1.0.1"
maintainers:
  - name: Akto API Security
keywords:
  - kafka
  - transformer
  - message-processing
